# ============================================================
# 动作配置文件 — 由 YAML 编辑器生成
# 生成时间: 2026/6/10 11:24:17
# 来源: lingxing_elements_V10_登录_cleaned.json
# ============================================================

page_url: "https://huizhixin.lingxing.com/login"
close_browser: true
actions:

  - index: 0
    step_name: "登录"
    action:
      type: click
      on_not_found: fail
      wait_for_element: false
      wait_before: 0.5
      wait_after: 0.5
      wait_strategy: timeout

  - index: 1
    step_name: "登录"
    action:
      type: fill
      on_not_found: fail
      wait_for_element: false
      value: "${ACCOUNT}"
      clear_first: true
      wait_before: 0.5
      wait_after: 0.5
      wait_strategy: timeout

  - index: 2
    step_name: "登录"
    action:
      type: fill
      on_not_found: fail
      wait_for_element: false
      value: "${PASSWORD}"
      clear_first: true
      wait_before: 0.5
      wait_after: 0.5
      wait_strategy: timeout

  - index: 3
    step_name: "登录"
    action:
      type: click
      on_not_found: fail
      wait_for_element: false
      wait_before: 0.5
      wait_after: 0.5
      wait_strategy: timeout